#!/usr/bin/env bash
#
# One-shot setup for TradeMyShow on a fresh Ubuntu 22.04/24.04 Azure VM.
#
# Installs Node, builds the app, runs it under systemd, and puts nginx in
# front of it. Safe to re-run: every step checks before it acts, so a failed
# run can simply be repeated rather than unpicked.
#
#   curl -fsSL <raw-url>/scripts/azure-vm-setup.sh -o setup.sh
#   chmod +x setup.sh
#   ./setup.sh
#
set -euo pipefail

APP_USER="${SUDO_USER:-$USER}"
APP_DIR="/opt/trademyshow"
DATA_DIR="/var/lib/trademyshow"
NODE_MAJOR=22
SERVICE=trademyshow

say()  { printf '\n\033[1;34m==>\033[0m %s\n' "$1"; }
ok()   { printf '    \033[0;32m✓\033[0m %s\n' "$1"; }
warn() { printf '    \033[0;33m!\033[0m %s\n' "$1"; }
die()  { printf '\n\033[0;31mERROR:\033[0m %s\n\n' "$1" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Run this with sudo:  sudo ./setup.sh"
command -v apt-get >/dev/null || die "This script expects Ubuntu or Debian."

# ---------------------------------------------------------------- questions
# Asked once, up front, so the rest runs unattended.

read -rp "GitHub repository URL [https://github.com/aspireitech/Trademyshow.git]: " REPO
REPO="${REPO:-https://github.com/aspireitech/Trademyshow.git}"

read -rp "Branch [claude/stock-analytics-ai-portal-j7ftsb]: " BRANCH
BRANCH="${BRANCH:-claude/stock-analytics-ai-portal-j7ftsb}"

read -rp "Domain name (blank = use the VM's IP address, no HTTPS): " DOMAIN
read -rp "Run as a SANDBOX demo with fake prices? [Y/n]: " SANDBOX_ANS
SANDBOX_ANS="${SANDBOX_ANS:-Y}"
SANDBOX="false"
[[ "$SANDBOX_ANS" =~ ^[Yy] ]] && SANDBOX="true"

# ---------------------------------------------------------------- packages
say "Installing system packages (2-3 minutes)"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
# python3/make/g++ are needed because better-sqlite3 compiles from source.
apt-get install -y -qq curl git nginx ufw python3 make g++ ca-certificates gnupg >/dev/null
ok "curl, git, nginx, build tools"

if ! command -v node >/dev/null || [[ "$(node -v | cut -c2- | cut -d. -f1)" -lt "$NODE_MAJOR" ]]; then
  say "Installing Node.js ${NODE_MAJOR}"
  mkdir -p /etc/apt/keyrings
  curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
    | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
  echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_MAJOR}.x nodistro main" \
    > /etc/apt/sources.list.d/nodesource.list
  apt-get update -qq
  apt-get install -y -qq nodejs >/dev/null
fi
ok "Node $(node -v)"

# ---------------------------------------------------------------- source
say "Fetching the application"

# git refuses to operate on a repository owned by another user. Earlier
# versions of this script handed the whole tree to the service account, so an
# update run would fail here; the exception is scoped to this one command
# rather than written into root's global config, and the ownership is put back
# below so it stops recurring.
git_app() { git -c safe.directory="$APP_DIR" -C "$APP_DIR" "$@"; }

if [[ -d "$APP_DIR/.git" ]]; then
  git_app fetch --quiet origin "$BRANCH"
  git_app checkout --quiet "$BRANCH"
  git_app reset --hard --quiet "origin/$BRANCH"
  ok "updated existing checkout"
else
  rm -rf "$APP_DIR"
  git clone --quiet --branch "$BRANCH" "$REPO" "$APP_DIR" \
    || die "Clone failed. If the repository is private, see PRIVATE REPOS in docs/DEPLOY-AZURE-VM.md"
  ok "cloned $BRANCH"
fi

# ---------------------------------------------------------------- secrets
say "Configuring"
mkdir -p "$DATA_DIR/contracts"

if [[ -f "$APP_DIR/.env.production" ]]; then
  warn "Keeping the existing .env.production (delete it to regenerate secrets)"
else
  AUTH_SECRET="$(openssl rand -hex 32)"
  CRON_SECRET="$(openssl rand -hex 32)"
  SITE_URL="http://$(curl -fsS --max-time 5 ifconfig.me 2>/dev/null || echo localhost)"
  [[ -n "$DOMAIN" ]] && SITE_URL="https://$DOMAIN"

  cat > "$APP_DIR/.env.production" <<ENVFILE
# Generated by azure-vm-setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
NODE_ENV=production
SANDBOX=${SANDBOX}
SITE_URL=${SITE_URL}
AUTH_SECRET=${AUTH_SECRET}
CRON_SECRET=${CRON_SECRET}
DB_PATH=${DATA_DIR}/trademyshow.db
CONTRACTS_DIR=${DATA_DIR}/contracts
# Live by default: unset means Yahoo Finance, then Stooq, then Finnhub if a
# key is present. Set it to "mock" only to force the simulation on.
MARKET_DATA_PROVIDER=auto

# Fill these in before charging anyone. The Terms page warns while they are blank.
LEGAL_COMPANY_NAME=
LEGAL_COMPANY_NUMBER=
LEGAL_ADDRESS=
LEGAL_GOVERNING_LAW=
LEGAL_FORUM=
LEGAL_CONTACT_EMAIL=

# Optional: everything below degrades gracefully when absent.
# GEMINI_API_KEY=
# STRIPE_SECRET_KEY=
# RESEND_API_KEY=
ENVFILE
  chmod 600 "$APP_DIR/.env.production"
  ok "generated .env.production with fresh secrets"
fi

# ---------------------------------------------------------------- build
say "Installing dependencies and building (3-5 minutes)"
cd "$APP_DIR"
npm ci --no-audit --no-fund >/dev/null 2>&1 || die "npm ci failed. Run 'npm ci' in $APP_DIR to see why."
ok "dependencies installed"
npm run build >/dev/null 2>&1 || die "Build failed. Run 'npm run build' in $APP_DIR to see why."
ok "application built"

id -u "$SERVICE" &>/dev/null || useradd --system --no-create-home --shell /usr/sbin/nologin "$SERVICE"

# The service account reads the application and writes only its own cache and
# data. Leaving the source root-owned means a compromised service cannot
# rewrite its own code, keeps the secrets file readable by root alone, and
# leaves later git operations conflict-free.
chown -R root:root "$APP_DIR"
chmod 600 "$APP_DIR/.env.production"
mkdir -p "$APP_DIR/.next/cache"
chown -R "$SERVICE":"$SERVICE" "$DATA_DIR" "$APP_DIR/.next"

# ---------------------------------------------------------------- service
say "Registering the background service"
cat > /etc/systemd/system/${SERVICE}.service <<UNIT
[Unit]
Description=TradeMyShow
After=network.target

[Service]
Type=simple
User=${SERVICE}
WorkingDirectory=${APP_DIR}
EnvironmentFile=${APP_DIR}/.env.production
Environment=PORT=3000
ExecStart=/usr/bin/npm run start
Restart=always
RestartSec=5

# The service needs nothing outside its own two directories.
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=${DATA_DIR} ${APP_DIR}/.next

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable --quiet ${SERVICE}
systemctl restart ${SERVICE}
sleep 4
systemctl is-active --quiet ${SERVICE} \
  || die "Service failed to start. Check:  sudo journalctl -u ${SERVICE} -n 50"
ok "service running"

# ---------------------------------------------------------------- nginx
say "Configuring the web server"
SERVER_NAME="${DOMAIN:-_}"
cat > /etc/nginx/sites-available/${SERVICE} <<NGINX
server {
    listen 80;
    server_name ${SERVER_NAME};

    # Let the app set its own security headers rather than duplicating them.
    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        proxy_read_timeout 300s;
    }
}
NGINX
ln -sf /etc/nginx/sites-available/${SERVICE} /etc/nginx/sites-enabled/${SERVICE}
rm -f /etc/nginx/sites-enabled/default
nginx -t >/dev/null 2>&1 || die "nginx config test failed. Run 'sudo nginx -t'."
systemctl reload nginx
ok "nginx proxying port 80 to the app"

ufw --force enable >/dev/null 2>&1 || true
ufw allow OpenSSH >/dev/null 2>&1 || true
ufw allow 'Nginx Full' >/dev/null 2>&1 || true
ok "firewall allows SSH, HTTP and HTTPS"

# ---------------------------------------------------------------- https
if [[ -n "$DOMAIN" ]]; then
  say "Requesting an HTTPS certificate for ${DOMAIN}"
  apt-get install -y -qq certbot python3-certbot-nginx >/dev/null
  if certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos \
       --register-unsafely-without-email --redirect >/dev/null 2>&1; then
    ok "HTTPS enabled and set to auto-renew"
  else
    warn "Certificate request failed — usually DNS not pointing here yet."
    warn "Fix the DNS A record, then run:  sudo certbot --nginx -d ${DOMAIN}"
  fi
fi

# ---------------------------------------------------------------- schedule
say "Scheduling the daily jobs"
CRON_SECRET_VALUE="$(grep '^CRON_SECRET=' "$APP_DIR/.env.production" | cut -d= -f2)"
cat > /etc/cron.d/${SERVICE} <<CRON
# TradeMyShow scheduled work. Times are UTC.
SHELL=/bin/bash
CS=${CRON_SECRET_VALUE}
30 10 * * 1-5 root curl -sf -X POST -H "Authorization: Bearer \$CS" "http://127.0.0.1:3000/api/cron?job=market-data" >/dev/null
0  11 * * 1-5 root curl -sf -X POST -H "Authorization: Bearer \$CS" "http://127.0.0.1:3000/api/cron?job=digest&period=daily" >/dev/null
0  13 * * 6   root curl -sf -X POST -H "Authorization: Bearer \$CS" "http://127.0.0.1:3000/api/cron?job=digest&period=weekly" >/dev/null
0  *  * * *   root curl -sf -X POST -H "Authorization: Bearer \$CS" "http://127.0.0.1:3000/api/cron?job=alerts" >/dev/null
0  3  * * *   root curl -sf -X POST -H "Authorization: Bearer \$CS" "http://127.0.0.1:3000/api/cron?job=purge" >/dev/null
CRON
chmod 644 /etc/cron.d/${SERVICE}
ok "market data, digests, alerts and cleanup scheduled"

# ---------------------------------------------------------------- seed
if [[ "$SANDBOX" == "true" ]]; then
  say "Adding demo data"
  if curl -sf -X POST -H "Authorization: Bearer ${CRON_SECRET_VALUE}" \
      "http://127.0.0.1:3000/api/cron?job=seed" >/dev/null; then
    ok "demo accounts and watchlists created"
  else
    warn "Seeding failed. Retry later with the command in the summary below."
  fi
fi

# ---------------------------------------------------------------- summary
PUBLIC_URL="$(grep '^SITE_URL=' "$APP_DIR/.env.production" | cut -d= -f2)"
HEALTH="$(curl -sf http://127.0.0.1:3000/api/health || echo '{}')"

cat <<SUMMARY

────────────────────────────────────────────────────────────
 TradeMyShow is running.

   Open:      ${PUBLIC_URL}
   Health:    ${PUBLIC_URL}/api/health
SUMMARY

if [[ "$SANDBOX" == "true" ]]; then
cat <<SUMMARY
   Demo login:   demo@trademyshow.com  /  Sandbox!Demo2026
   Admin login:  admin@trademyshow.com /  Sandbox!Admin2026
SUMMARY
fi

cat <<SUMMARY

 Useful commands
   sudo systemctl status ${SERVICE}      is it running?
   sudo journalctl -u ${SERVICE} -f      watch the logs
   sudo systemctl restart ${SERVICE}     restart it
   sudo nano ${APP_DIR}/.env.production  change settings

 To update to the latest code
   sudo ./setup.sh

 Before charging anyone, fill in the LEGAL_ values in
 ${APP_DIR}/.env.production — the Terms page warns while they are blank.
────────────────────────────────────────────────────────────

SUMMARY

echo "$HEALTH" | grep -q '"status":"ok"' \
  && ok "Health check passed" \
  || warn "Health check did not report ok — see ${PUBLIC_URL}/api/health"
